<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSlideTable extends Doctrine_Table
{
	public function createQuery($alias = '')
	{
		return parent::createQuery($alias)->orderBy('created_at DESC');
	}
}