<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSlideshowSlideTable extends Doctrine_Table
{
  public function createQuery($alias = '')
  {
    return parent::createQuery($alias)->orderBy(($alias ? $alias.'.' : '').'position ASC');
  }
  
  /**
   * Send an array from the sortable_element tag and it will 
   * update the sort order to match
   *
   * @param string $order
   * @return void
   */
  public function sort(array $order)
  {
    $order = array_filter($order);

    $this->createQuery('a')->update()
         ->set('a.position = ?', null)
         ->whereIn('a.id', array_keys($order))
         ->execute();
    
    $objects = $this->createQuery()->whereIn('id', array_keys($order))->execute();
    
    foreach ($objects as $object) 
    {
      $object->position = $order[$object->id];
      $object->save();
    }
  }
}