<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSlide extends BaseSlide
{
	public function hasTitle()
	{
		return $this['title'] != '' && $this['title'] != null;
	}
	public function hasDescription()
	{
		return $this['description'] != '' && $this['description'] != null;
	}
	public function getUploadPath()
	{
		return 'uploads/slideshow';
	}
	public function getImagepath()
	{
		return '/'.$this->getUploadPath() .'/'.$this->getImage();
	}
}