<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSlideshow extends BaseSlideshow
{
	public function getOrderedSlideshowSlides()
	{
		return Doctrine::getTable('SlideshowSlide')->createQuery('s')
											->andWhere('s.slideshow_id = ?', $this->id)
											->orderBy('position ASC')
											->execute();
	}
	public function getOrderedSlides()
	{
		return Doctrine::getTable('Slide')->createQuery('s')
		                  ->innerJoin('s.SlideshowSlide ss')
											->andWhere('ss.slideshow_id = ?', $this->id)
											->orderBy('ss.position ASC')
											->execute();
	}
	public function getOption($option, $default = null)
	{
    $options = csSlideshowToolkit::stringToArray($this->options);
    return isset($options[$option]) ? $options[$option] : $default;
	}
}