all:
  slideshow:
    defaults:   
      speed:      fast
      timeout:    5000
      fx:         null
    renderers:  
      SlideshowJQueryCycleRenderer: 'JQuery Cycle'
      SlideshowGoogleSlideshow2Renderer: 'Google Slideshow 2'
      
      # Add custom renderers to this list.  The format is $class => $readable_name