generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Slide
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          slide_admin
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        display:  [_thumbnail, title]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
