generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Slideshow
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          slideshow_admin
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display: [name, width, height, options, renderer, slides_list, _slide_order, _new_slide]
      edit:    ~
      new:     ~
