Slideshow:
  actAs: [Timestampable]
  columns:
    name: string(255)
    width: string(255)
    height: string(255)
    renderer:
      default:  SlideshowJQueryCycleRenderer
      type:   string(255)
    options:
      type:  clob  
  relations:
    Slides:
      class: Slide
      refClass: SlideshowSlide
      foreignAlias: Slideshows

Slide:
  actAs: [Timestampable]
  columns:
    image:  
      type:   string(255)
    title:
      type:   string(255)
    description:  
      type:   clob

SlideshowSlide:
  indexes: 
    sortable:
      type:     unique
      fields:   [position, slideshow_id]
    slideshow_slides:
      type:     unique
      fields:   [slide_id, slideshow_id]
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    slideshow_id:
      type: integer
      primary: true
    slide_id:
      type: integer
      primary: true
    position:
      type: integer(4)
  relations:
    Slideshow:
      onDelete: CASCADE
      foreignAlias: SlideshowSlides
    Slide:
      onDelete: CASCADE
      foreignAlias: SlideshowSlides